### ISSUE TITLE
Look into OpenCPU

### ISSUE THREAD

**Issue by arnfinn** [SKDE-Felles/SKDEr#3]
- https://github.com/opencpu/opencpu
- https://www.opencpu.org/posts/opencpu-with-docker/

This might be something to consider together with or instead of ShinyProxy.

**Comment by arnfinn** [comment]
To keep Are in the loop: @areedv

**Comment by yte0** [comment]
A paper that discusses the openCPU system:
    https://arxiv.org/abs/1406.4806

and the openCPU server manual
    https://opencpu.github.io/server-manual/opencpu-server.pdf

**Comment by yte0** [comment]
The openCPU system provids an HTTP API that can be used to connect a separete statistical computation in R to the rest of the webapp. The webapp can be structured as a typical R-package, where the R functions can be located in the R folder, and the webapp related scripts can be add to /inst/www folder. The R functions can then be accessed by the web related scripts using the openCPU API.

OpenCPU can be implemented in  an interactive R session or on server that builds on apache and nginx. The implementation steps are discribed in the openCPU server manual.
